postgres:
  host: 10.92.5.104
  database: finance
  user: finance
  password: ij8Soogak

s3:
  aws_access_key_id : AKIA2NQ5NY3EHL4ZA4SD
  aws_secret_access_key : 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
  bucket: zebrainy
